#import <Foundation/Foundation.h>
#ifndef Constants_h
#define Constants_h

FOUNDATION_EXPORT NSString *const TYPE_INLINE_AD;
FOUNDATION_EXPORT NSString *const TYPE_INTERSTITIAL_AD;

FOUNDATION_EXPORT NSString *const AD_LOADED;
FOUNDATION_EXPORT NSString *const AD_DEFAULT_LOADED;
FOUNDATION_EXPORT NSString *const AD_LOAD_FAILED;
FOUNDATION_EXPORT NSString *const AD_WILL_BEGIN_ACTION;
FOUNDATION_EXPORT NSString *const AD_ACTION_FINISHED;
FOUNDATION_EXPORT NSString *const AD_WILL_RESIZE;
FOUNDATION_EXPORT NSString *const AD_RESIZE_FINISHED;
FOUNDATION_EXPORT NSString *const AD_WILL_EXPAND;
FOUNDATION_EXPORT NSString *const AD_EXPAND_FINISHED;
FOUNDATION_EXPORT NSString *const AD_WILL_CLOSE;
FOUNDATION_EXPORT NSString *const AD_CLOSED;

FOUNDATION_EXPORT NSString *const MESSAGE_OPENED;
FOUNDATION_EXPORT NSString *const MESSAGE_DISMISSED;
FOUNDATION_EXPORT NSString *const REGISTER_DEVICE_TOKEN;

#endif
