import InlineAdView from './views/InlineAdView';
import InterstitialAdView from './views/InterstitialAdView';
import * as Constants from './Constants';
export declare function multiply(a: number, b: number): Promise<number>;
export declare function newPage(uri: string): any;
export declare function getSessionID(callback: (id: string) => void): void;
export declare function getSdkVersion(callback: (version: string) => void): void;
export declare function addAppEvent(eventKey: string, data: Object | null): void;
export declare function identity(value: string, type: string): Promise<boolean>;
export declare function detachIdentity(): Promise<any>;
export declare function getTenantID(callback: (id: string) => void): void;
export declare function getDeviceID(callback: (id: string) => void): void;
export declare function getTagServer(callback: (id: string) => void): void;
export declare function getAppVersion(callback: (version: string) => void): void;
export declare function registerForMobileMessage(token: string): void;
export declare function handleMobileMessage(data: Object, callback: (success: boolean) => void): void;
export { InlineAdView };
export { InterstitialAdView };
declare const SASMobileMessagingEvent: any;
declare const AdDelegateEvent: any;
export { SASMobileMessagingEvent };
export { AdDelegateEvent };
export { Constants };
